blend:
  common:
    num_blend_layers: 1
    minimum_network_size: 32
    protocol_name: /logos-blockchain-testnet-v0.1.2/blend/1.0.0
    data_replication_factor: 0
  core:
    scheduler:
      cover:
        message_frequency_per_round: 1.0
        intervals_for_safety_buffer: 100
      delayer:
        maximum_release_delay_in_rounds: 1
    minimum_messages_coefficient: 1
    normalization_constant: 1.03
    activity_threshold_sensitivity: 1
network:
  kademlia_protocol_name: /logos-blockchain-testnet-v0.1.2/kad/1.0.0
  identify_protocol_name: /logos-blockchain-testnet-v0.1.2/identify/1.0.0
  chain_sync_protocol_name: /logos-blockchain-testnet-v0.1.2/chainsync/1.0.0
cryptarchia:
  epoch_config:
    epoch_stake_distribution_stabilization: 3
    epoch_period_nonce_buffer: 3
    epoch_period_nonce_stabilization: 4
  security_param: 30
  slot_activation_coeff:
    numerator: 1
    denominator: 20
  learning_rate: 0.5
  sdp_config:
    service_params:
      BN:
        lock_period: 10
        inactivity_period: 1
        retention_period: 1
        timestamp: 0
    min_stake:
      threshold: 1
      timestamp: 0
  gossipsub_protocol: /logos-blockchain-testnet-v0.1.2/cryptarchia/1.0.0
  genesis_state:
    mantle_tx:
      ops:
      - opcode: 0
        payload:
          inputs: []
          outputs:
          - value: 100000
            pk: f1a57ec7b85a73636372239c081f7b8986d81c82e3edadd7c50b13f8d6b09808
          - value: 1
            pk: d114b1cbaf0e0b10d00449a3e0fcd789710a0bf9c63de9185c07e573144bde08
          - value: 100
            pk: 859d98b2eb9f6253bf908ca2b1fc445b517b7cb5e7b6280e2c1da4f19304c71d
          - value: 100000
            pk: 7da3dd5d15672d6f6ebc6378d3b7f8e818b1b719b1e88f96a08ca1b317513019
          - value: 1
            pk: de0547b5c5cb44f7a3b156d757087a6e4b23e977fde1e0cc133823e39ac68327
          - value: 100
            pk: 7215983b8b7440c7bc61a8252f1d6cb5f6cd2c8e098b9dc17a43145af93d1900
          - value: 100000
            pk: dfc3c8e7d28ac773a17919a5567d427e1a2786ef3355201285da209bbefff61d
          - value: 1
            pk: b64e26c88f58b4a6096a6e5b98b4365355c294835eee8cec58356c1d6b4b8502
          - value: 100
            pk: 670b1a36742173c0310ec3ffb352afe8430d938619334ce57a8fb2bcd24dca1e
          - value: 100000
            pk: ac2d8fce76640804e05a6e1f5da5a0ae784e05a5d1b9f917872cf8664f6bce1c
          - value: 1
            pk: 90678379b2ed5316d870eb51e8c20ffaf891ade0ed80a8775f4136a8979fac27
          - value: 100
            pk: 605199d3e793d342f1f0457c0ada288efc61d455e3b576e70af14b1651a08c06
          - value: 18446744073709151211
            pk: fcadf75488f8048bd4db210e55b6da2c1960af0fda9c3ce73bb79b842c688a14
      - opcode: 17
        payload:
          channel_id: '0000000000000000000000000000000000000000000000000000000000000000'
          inscription:
          - 112
          - 114
          - 111
          - 99
          - 101
          - 115
          - 115
          - 95
          - 115
          - 116
          - 97
          - 114
          - 116
          - 95
          - 110
          - 111
          - 110
          - 99
          - 101
          - 61
          - 49
          - 56
          - 97
          - 53
          - 102
          - 51
          - 98
          - 50
          - 48
          - 55
          - 55
          - 54
          - 57
          - 55
          - 50
          - 55
          - 45
          - 48
          - 48
          - 48
          - 48
          - 48
          - 48
          - 48
          - 49
          - 44
          - 32
          - 116
          - 101
          - 115
          - 116
          - 95
          - 101
          - 110
          - 116
          - 114
          - 111
          - 112
          - 121
          - 61
          - 54
          - 49
          - 52
          - 52
          - 56
          - 97
          - 51
          - 98
          - 55
          - 57
          - 99
          - 102
          - 52
          - 50
          - 97
          - 49
          parent: '0000000000000000000000000000000000000000000000000000000000000000'
          signer: '0000000000000000000000000000000000000000000000000000000000000000'
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/65.109.51.37/udp/3400/quic-v1
          provider_id: 59c662860b737f4e2515599adb3434856db8070b373a449ff66955ad3da6b473
          zk_id: 6b2bcd3029fba573cff0c332dc4de7430faf5e261383d693d8dbb5b97665660a
          locked_note_id: 3683046167f2329c325bc49b692f8530775a0ea552d5059b8c5b05ee6d1ca812
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/65.109.51.37/udp/3401/quic-v1
          provider_id: 7fce82aa171b349a40f2a98ce9a05b5db62415adfd3ab4ffea6f214443d5909d
          zk_id: ae9a47f76c9a2c00c40310cc82a1da9f5292af9ee223b898c38478c85fd39515
          locked_note_id: 47aeab97e93399a1c3411ab1743b73856c91a6c23e5efc3187f4aa1aec39481b
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/65.109.51.37/udp/3402/quic-v1
          provider_id: da8060ee71506bcbf1ac50973ad6dedc3a6cae69139b9d12bfd9c80c4785f6b0
          zk_id: 4114009ea9da81c5fcb680eca33129fb3fe166af733d25a23ac2da567ee84c19
          locked_note_id: 1cdca82d608dd462963b319eb183bfc94d835571cc7834df376fbc1d64ab7309
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/65.109.51.37/udp/3403/quic-v1
          provider_id: f6807fc50fbd4ef5f7fe1aaef037ee78d23233e60de802da36bfbb64215800fe
          zk_id: 4d705c711b7c99fc041576c0c5412934cd86f3369d88c9f451e786c0e396fb1c
          locked_note_id: 7eb3dc8ec6d00ebf6e3a203d5c0c46937092c75fed5140ee6a23a0530641c302
      execution_gas_price: 0
      storage_gas_price: 0
    ops_proofs:
    - !ZkSig
      pi_a:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      pi_b:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      pi_c:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - NoProof
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 215
        - 94
        - 155
        - 112
        - 232
        - 53
        - 110
        - 238
        - 71
        - 219
        - 74
        - 74
        - 254
        - 31
        - 12
        - 94
        - 196
        - 114
        - 32
        - 99
        - 222
        - 53
        - 183
        - 226
        - 208
        - 11
        - 7
        - 18
        - 73
        - 51
        - 178
        - 156
        pi_b:
        - 73
        - 50
        - 174
        - 30
        - 137
        - 213
        - 63
        - 126
        - 224
        - 107
        - 244
        - 15
        - 219
        - 96
        - 195
        - 179
        - 142
        - 167
        - 98
        - 208
        - 14
        - 142
        - 251
        - 245
        - 18
        - 139
        - 66
        - 48
        - 132
        - 15
        - 105
        - 2
        - 255
        - 12
        - 231
        - 78
        - 234
        - 20
        - 205
        - 172
        - 207
        - 113
        - 100
        - 135
        - 89
        - 78
        - 106
        - 176
        - 106
        - 150
        - 72
        - 120
        - 110
        - 203
        - 178
        - 63
        - 244
        - 154
        - 79
        - 66
        - 31
        - 187
        - 66
        - 167
        pi_c:
        - 107
        - 205
        - 233
        - 118
        - 12
        - 235
        - 161
        - 212
        - 98
        - 58
        - 68
        - 201
        - 223
        - 185
        - 211
        - 44
        - 30
        - 121
        - 21
        - 16
        - 73
        - 67
        - 109
        - 195
        - 207
        - 59
        - 22
        - 11
        - 184
        - 5
        - 154
        - 0
      ed25519_sig:
      - 58
      - 59
      - 129
      - 188
      - 153
      - 34
      - 65
      - 161
      - 155
      - 158
      - 212
      - 2
      - 10
      - 57
      - 30
      - 189
      - 49
      - 141
      - 176
      - 103
      - 229
      - 175
      - 36
      - 200
      - 198
      - 151
      - 178
      - 36
      - 154
      - 43
      - 51
      - 13
      - 80
      - 105
      - 19
      - 190
      - 131
      - 206
      - 235
      - 66
      - 53
      - 166
      - 43
      - 145
      - 53
      - 205
      - 142
      - 86
      - 151
      - 48
      - 154
      - 62
      - 146
      - 183
      - 128
      - 233
      - 116
      - 85
      - 125
      - 35
      - 65
      - 254
      - 198
      - 3
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 127
        - 17
        - 120
        - 251
        - 129
        - 49
        - 193
        - 137
        - 98
        - 87
        - 33
        - 28
        - 204
        - 157
        - 190
        - 182
        - 20
        - 203
        - 232
        - 29
        - 167
        - 196
        - 208
        - 24
        - 218
        - 249
        - 229
        - 251
        - 148
        - 133
        - 197
        - 17
        pi_b:
        - 94
        - 182
        - 38
        - 161
        - 191
        - 196
        - 60
        - 68
        - 190
        - 31
        - 29
        - 45
        - 180
        - 166
        - 201
        - 113
        - 255
        - 250
        - 254
        - 194
        - 75
        - 51
        - 93
        - 31
        - 77
        - 87
        - 31
        - 230
        - 112
        - 178
        - 246
        - 14
        - 82
        - 200
        - 8
        - 192
        - 166
        - 163
        - 9
        - 71
        - 4
        - 124
        - 9
        - 55
        - 117
        - 119
        - 143
        - 101
        - 103
        - 32
        - 18
        - 60
        - 73
        - 87
        - 186
        - 194
        - 155
        - 35
        - 10
        - 14
        - 249
        - 36
        - 199
        - 129
        pi_c:
        - 38
        - 82
        - 46
        - 120
        - 218
        - 243
        - 142
        - 132
        - 111
        - 91
        - 117
        - 229
        - 216
        - 163
        - 203
        - 109
        - 144
        - 50
        - 228
        - 95
        - 166
        - 147
        - 186
        - 11
        - 182
        - 55
        - 63
        - 193
        - 47
        - 33
        - 110
        - 33
      ed25519_sig:
      - 123
      - 21
      - 104
      - 251
      - 166
      - 83
      - 8
      - 80
      - 68
      - 152
      - 229
      - 191
      - 146
      - 132
      - 247
      - 90
      - 84
      - 84
      - 57
      - 189
      - 61
      - 118
      - 229
      - 52
      - 70
      - 10
      - 198
      - 57
      - 144
      - 133
      - 76
      - 96
      - 126
      - 11
      - 214
      - 94
      - 106
      - 247
      - 146
      - 37
      - 35
      - 108
      - 128
      - 178
      - 222
      - 244
      - 22
      - 138
      - 53
      - 235
      - 113
      - 102
      - 154
      - 28
      - 63
      - 21
      - 85
      - 206
      - 29
      - 202
      - 199
      - 172
      - 76
      - 1
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 69
        - 200
        - 156
        - 4
        - 244
        - 236
        - 243
        - 227
        - 137
        - 85
        - 5
        - 107
        - 152
        - 28
        - 215
        - 60
        - 162
        - 206
        - 151
        - 133
        - 241
        - 66
        - 46
        - 88
        - 37
        - 60
        - 133
        - 245
        - 0
        - 184
        - 221
        - 160
        pi_b:
        - 243
        - 128
        - 47
        - 196
        - 0
        - 137
        - 37
        - 237
        - 145
        - 1
        - 236
        - 210
        - 200
        - 42
        - 183
        - 20
        - 189
        - 75
        - 5
        - 64
        - 95
        - 231
        - 106
        - 24
        - 62
        - 186
        - 130
        - 154
        - 120
        - 0
        - 164
        - 15
        - 22
        - 91
        - 31
        - 228
        - 36
        - 212
        - 62
        - 104
        - 35
        - 198
        - 237
        - 180
        - 211
        - 23
        - 82
        - 89
        - 134
        - 138
        - 254
        - 132
        - 24
        - 6
        - 2
        - 174
        - 209
        - 58
        - 218
        - 132
        - 145
        - 85
        - 239
        - 8
        pi_c:
        - 105
        - 48
        - 54
        - 245
        - 100
        - 167
        - 5
        - 162
        - 144
        - 153
        - 66
        - 168
        - 19
        - 217
        - 239
        - 210
        - 36
        - 19
        - 196
        - 25
        - 194
        - 14
        - 133
        - 57
        - 86
        - 206
        - 122
        - 133
        - 224
        - 233
        - 63
        - 3
      ed25519_sig:
      - 23
      - 194
      - 155
      - 211
      - 142
      - 13
      - 3
      - 13
      - 104
      - 0
      - 205
      - 239
      - 165
      - 135
      - 101
      - 183
      - 104
      - 24
      - 34
      - 82
      - 128
      - 92
      - 210
      - 64
      - 55
      - 47
      - 91
      - 67
      - 193
      - 91
      - 253
      - 9
      - 33
      - 178
      - 234
      - 48
      - 167
      - 116
      - 23
      - 156
      - 82
      - 120
      - 25
      - 48
      - 166
      - 15
      - 183
      - 7
      - 55
      - 44
      - 217
      - 249
      - 180
      - 100
      - 229
      - 154
      - 43
      - 39
      - 113
      - 238
      - 93
      - 184
      - 238
      - 0
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 253
        - 163
        - 186
        - 123
        - 141
        - 120
        - 107
        - 109
        - 224
        - 119
        - 59
        - 216
        - 19
        - 69
        - 229
        - 200
        - 194
        - 210
        - 218
        - 45
        - 200
        - 151
        - 98
        - 226
        - 189
        - 208
        - 15
        - 93
        - 61
        - 54
        - 31
        - 13
        pi_b:
        - 35
        - 131
        - 44
        - 55
        - 185
        - 123
        - 202
        - 217
        - 175
        - 5
        - 161
        - 170
        - 77
        - 10
        - 52
        - 69
        - 233
        - 88
        - 28
        - 111
        - 34
        - 248
        - 6
        - 51
        - 229
        - 156
        - 57
        - 212
        - 200
        - 142
        - 122
        - 21
        - 243
        - 100
        - 200
        - 123
        - 70
        - 147
        - 210
        - 219
        - 211
        - 171
        - 217
        - 23
        - 2
        - 254
        - 149
        - 202
        - 229
        - 249
        - 15
        - 213
        - 138
        - 108
        - 41
        - 219
        - 101
        - 79
        - 75
        - 61
        - 60
        - 163
        - 103
        - 156
        pi_c:
        - 40
        - 185
        - 25
        - 106
        - 66
        - 41
        - 18
        - 124
        - 144
        - 44
        - 126
        - 225
        - 60
        - 201
        - 105
        - 51
        - 28
        - 155
        - 109
        - 199
        - 124
        - 62
        - 103
        - 31
        - 72
        - 121
        - 106
        - 222
        - 177
        - 51
        - 65
        - 24
      ed25519_sig:
      - 163
      - 166
      - 24
      - 215
      - 16
      - 221
      - 27
      - 20
      - 224
      - 122
      - 193
      - 48
      - 236
      - 172
      - 55
      - 2
      - 194
      - 77
      - 109
      - 178
      - 99
      - 41
      - 7
      - 6
      - 27
      - 158
      - 107
      - 174
      - 223
      - 201
      - 246
      - 113
      - 157
      - 217
      - 123
      - 216
      - 219
      - 51
      - 118
      - 105
      - 254
      - 8
      - 92
      - 35
      - 223
      - 115
      - 52
      - 39
      - 141
      - 49
      - 57
      - 243
      - 150
      - 220
      - 130
      - 190
      - 175
      - 132
      - 74
      - 255
      - 163
      - 120
      - 226
      - 8
  faucet_pk: fcadf75488f8048bd4db210e55b6da2c1960af0fda9c3ce73bb79b842c688a14
time:
  slot_duration: '1.000000000'
  chain_start_time: 2026-04-13 15:19:31.0 +00:00:00
mempool:
  pubsub_topic: /logos-blockchain-testnet-v0.1.2/mempool/1.0.0
