# Snapshot aligned with cfgsync "deployment-settings" (devnet).
# Canonical: https://devnet.blockchain.logos.co/web/cfgsync/deployment-settings

blend:
  common:
    num_blend_layers: 1
    minimum_network_size: 32
    protocol_name: /logos-blockchain-testnet-v0.1.2/blend/1.0.0
    data_replication_factor: 0
  core:
    scheduler:
      cover:
        message_frequency_per_round: 1.0
        intervals_for_safety_buffer: 100
      delayer:
        maximum_release_delay_in_rounds: 1
    minimum_messages_coefficient: 1
    normalization_constant: 1.03
    activity_threshold_sensitivity: 1

network:
  kademlia_protocol_name: /logos-blockchain-testnet-v0.1.2/kad/1.0.0
  identify_protocol_name: /logos-blockchain-testnet-v0.1.2/identify/1.0.0
  chain_sync_protocol_name: /logos-blockchain-testnet-v0.1.2/chainsync/1.0.0

cryptarchia:
  epoch_config:
    epoch_stake_distribution_stabilization: 3
    epoch_period_nonce_buffer: 3
    epoch_period_nonce_stabilization: 4
  security_param: 30
  slot_activation_coeff:
    numerator: 1
    denominator: 20
  learning_rate: 0.5
  sdp_config:
    service_params:
      BN:
        lock_period: 10
        inactivity_period: 1
        retention_period: 1
        timestamp: 0
    min_stake:
      threshold: 1
      timestamp: 0
  gossipsub_protocol: /logos-blockchain-testnet-v0.1.2/cryptarchia/1.0.0
  genesis_state:
    mantle_tx:
      ops:
        - opcode: 0
          payload:
            inputs: ''
            outputs: ''
        - opcode: 17
          payload:
            channel_id: ''
            inscription: ''
            parent: ''
            signer: ''
        - opcode: 32
          payload:
            service_type: ''
            locators: ''
            provider_id: ''
            zk_id: ''
            locked_note_id: ''
      ops_proofs:
        - !ZkSig
          pi_a: ''
          pi_b: ''
          pi_c: ''
      execution_gas_price: ''
      storage_gas_price: ''
    faucet_pk: ''

time:
  slot_duration: '1.000000000'
  chain_start_time: 2026-04-13 15:19:31.0 +00:00:00

mempool:
  pubsub_topic: /logos-blockchain-testnet-v0.1.2/mempool/1.0.0
